Macro button customized
jsebold666/TazUO pull request #78
Opened 2023-03-30 04:56 UTC by elderwyn

Here is a solid foundation to the Customized Macro Buttons.
Look forward to your comments. Not sure how we can directly tie into the custom artwork as your described.
Maybe  ArtLoader.Instance.GetStaticTexture  ??

2023-03-30 11:51 UTC, bittiez commented
> Not sure how we can directly tie into the custom artwork as your described. Maybe ArtLoader.Instance.GetStaticTexture ??
Custom artwork is done automatically now via the PNGLoader and `/ExternalImages/` directory

2023-03-30 12:09 UTC, bittiez requested changes

2023-03-30 12:09 UTC, bittiez commented on src/ClassicUO.Client/Game/Managers/MacroManager.cs
> +            writer.WriteAttributeString(nameof(HideLabel).ToLower(), HideLabel.ToString());
When writing the xml data using a static string would be better, if these class names are ever changed it will break the saves
So replace these `nameof(HideLabel).ToLower()` with strings like "hideLabel"

2023-03-30 12:09 UTC, bittiez commented on src/ClassicUO.Client/Game/UI/Controls/MacroControl.cs
> +            _hotkeyBox.X = _keyBinding.Width + 5;
This should be `_hotkeyBox.X = _keyBinding.X + _keyBinding.Width + 5;` in case the keybinding is ever moved

2023-03-30 12:09 UTC, bittiez commented on src/ClassicUO.Client/Game/UI/Controls/MacroControl.cs
> +                    "Keybinding:",
I would change this text to `Hotkey` to better match the uo style of using hotkey's. Keybinding is the same thing but not many people say keybinding so it sounds a little weird

2023-03-30 12:09 UTC, bittiez commented on src/ClassicUO.Client/Game/UI/Controls/MacroControl.cs
> +                GameActions.OpenMacroButtonEditor(Macro, pos);
I would rather leave GameActions unchanged and just open the gump from here, one less file to change, and there isn't really a need for it to be in GameActions


Also if I understand correctly this would open the button editor every time you open the macro's ui instead of waiting for them to click the button?

2023-03-30 12:09 UTC, bittiez commented on src/ClassicUO.Client/Game/UI/Controls/MacroControl.cs
> +            for (MacroObject obj = (MacroObject)Macro.Items; obj != null; obj = (MacroObject)obj.Next)
This change doesn't improve on anything, no need to change it

2023-03-30 12:09 UTC, bittiez commented on src/ClassicUO.Client/Game/UI/Controls/MacroControl.cs
> +                    GameActions.OpenMacroButtonEditor(Macro, null);
I would rather leave GameActions unchanged and just open the gump from here, one less file to change, and there isn't really a need for it to be in GameActions

2023-03-30 12:09 UTC, bittiez commented on src/ClassicUO.Client/Game/UI/Gumps/MacroButtonGump.cs
> +        private bool _isMouseOver;
isMouseOver is already built in to all Controls, this is unnecessary

2023-03-30 22:57 UTC, elderwyn commented
I will get these comments addressed tonight, just got off work

2023-03-31 22:32 UTC, bittiez requested changes

2023-03-31 22:32 UTC, bittiez commented on src/ClassicUO.Client/Game/Managers/MacroManager.cs
> +            if (bool.TryParse(xml.GetAttribute("hidelabel"), out var hide)){
These work, but they can also be simplified to this:
```csharp 
bool.TryParse(xml.GetAttribute("hidelabel"), out var HideLabel)
```

2023-04-01 00:41 UTC, merged